### ISSUE TITLE
你好，想知道EfficientNet训练时是使用哪个数据集呀？

### ISSUE THREAD

**Issue by muxuen** [bzhwdeddbzsh/ding_bao_DMS#9]
是Driver Monitoring Dataset吗？
但我发现class_indices.json和这个数据集默认的标签是不一样的，而且这个数据集是视频模式的，所以有点懵

**Comment by NeizhiTouhu** [comment]
确实是DMD，还混了一部分[State Farm Distracted Driver Detection](https://www.kaggle.com/competitions/state-farm-distracted-driver-detection)。标签部分DMD原本的并不太符合我们的需要，所有有一些删减混合。实际使用的时候我们是把视频提取成一帧一帧去做的训练。
这个模型老实讲很简单也不是那么准确，也许可以换用更新的骨干或者加入时间注意力去进一步研究；又有什么问题欢迎随时交流

**Comment by muxuen** [comment]
> 确实是DMD，还混了一部分[State Farm Distracted Driver Detection](https://www.kaggle.com/competitions/state-farm-distracted-driver-detection)。标签部分DMD原本的并不太符合我们的需要，所有有一些删减混合。实际使用的时候我们是把视频提取成一帧一帧去做的训练。 这个模型老实讲很简单也不是那么准确，也许可以换用更新的骨干或者加入时间注意力去进一步研究；又有什么问题欢迎随时交流

好的！！非常感谢
